const cards=[
{country:'🇺🇦 UKRAINE',palette:['#314d63','#c5a646'],tags:['政治','復興','経済'],title:'政府、復旧予算の追加配分案を発表　住宅再建を最優先に',summary:'追加の復旧予算を住宅再建へ重点配分する方針。対象地域と財源が次の焦点になる。',source:'Kyiv Independent',image:null,what:'追加予算の配分先として、損壊住宅の再建を優先する方針が示されました。',why:'住宅再建は避難者の帰還、地方経済、自治体財政に直接影響します。',watch:'対象地域と財源の正式決定。'},
{country:'🇺🇸 WORLD',palette:['#5a2630','#26354d'],tags:['経済','市場'],title:'米国の消費者物価、伸びが鈍化　市場は利下げ時期を再評価',summary:'物価上昇率が予想を下回り、金利見通しが変化。ドルと株式市場にも反応が出た。',source:'Reuters',image:null,what:'最新の消費者物価統計が市場予想を下回りました。',why:'米金利は為替、資金調達、欧州や新興国の市場にも広く影響します。',watch:'次回FOMCまでの雇用・物価指標。'},
{country:'🇪🇺 EUROPE',palette:['#233d67','#9d8439'],tags:['制裁','外交','安全保障'],title:'EU、対ロ追加制裁で合意　エネルギーと金融への規制を強化',summary:'新たな制裁パッケージがまとまり、エネルギー収入と金融取引への制限が強まる。',source:'European Commission',image:null,what:'EU加盟国が追加制裁の主要項目で合意しました。',why:'ロシアの戦費調達と欧州企業の取引双方に影響するためです。',watch:'各国での実施時期と例外規定。'},
{country:'🇺🇦 WAR',palette:['#5a3030','#9f6738'],tags:['戦況','軍事'],title:'東部戦線で攻撃方向に変化　複数地点の動きを確認',summary:'占領面積よりも攻撃軸の変化が重要。複数の公開情報から方向転換が確認された。',source:'HATO Desk',image:null,what:'複数地点で部隊移動と攻撃方向の変化が確認されています。',why:'攻撃軸の変化は補給、予備兵力、次の重点地域を読む材料になります。',watch:'48時間以内の部隊配置と補給線の変化。'}
];
let index=0,history=[],understood=new Set(),drag=null,toastTimer=null,detailStartX=0;
const $=s=>document.querySelector(s),deck=$('#deck'),stage=$('#cardStage'),intro=$('#batchIntro'),clear=$('#clearScreen'),detail=$('#detail');
function flagFromCountry(c){return c.split(' ')[0]||'🌍'}
function renderDeck(){deck.innerHTML='';$('#position').textContent=Math.min(index+1,cards.length);$('#total').textContent=cards.length;if(index>=cards.length){stage.classList.add('hidden');clear.classList.remove('hidden');$('#clearDone').textContent=cards.length;$('#clearTotal').textContent=cards.length;return;}for(let p=Math.min(2,cards.length-1-index);p>=0;p--){const d=cards[index+p];const el=document.createElement('article');el.className='news-card'+(p===1?' back1':p===2?' back2':'');el.dataset.pos=p;const [a,b]=d.palette;el.innerHTML=`<div class="country-band" style="background:linear-gradient(90deg,${a},${b})"></div><div class="card-content"><div class="card-head"><div class="country-label">${d.country}</div><div class="save">♡</div></div><div class="tags card-tags">${d.tags.map(t=>`<span class="tag">${t}</span>`).join('')}</div><h2 class="card-title">${d.title}</h2><p class="card-summary">${d.summary}</p><div class="source">${d.source}</div><div class="visual"><div class="flag-fallback" style="background:linear-gradient(145deg,${a},${b});">${flagFromCountry(d.country)}</div></div>${understood.has(index+p)?'<div class="understood">理解できた ✓</div>':''}<div class="swipe-badge left">知ってる</div><div class="swipe-badge right">もっと知る</div></div>`;deck.appendChild(el);}bindSwipe();}
function topCard(){return deck.querySelector('.news-card[data-pos="0"]')}
function bindSwipe(){const c=topCard();if(!c)return;const start=(x,y,id)=>{drag={x,y,id};c.style.transition='none'};const move=(x,y)=>{if(!drag)return;const dx=x-drag.x,dy=y-drag.y;if(Math.abs(dy)>Math.abs(dx)&&Math.abs(dy)>16)return;c.style.transform=`translateX(${dx}px) rotate(${dx/24}deg)`;c.querySelector('.swipe-badge.left').style.opacity=Math.max(0,Math.min(1,-dx/95));c.querySelector('.swipe-badge.right').style.opacity=Math.max(0,Math.min(1,dx/95));};const end=x=>{if(!drag)return;const dx=x-drag.x;drag=null;c.style.transition='transform .25s cubic-bezier(.2,.8,.2,1),opacity .22s ease';if(dx<-90)acceptKnown(c);else if(dx>90)openMore(c);else reset(c)};c.addEventListener('touchstart',e=>{const t=e.touches[0];start(t.clientX,t.clientY,'t')},{passive:true});c.addEventListener('touchmove',e=>{const t=e.touches[0];move(t.clientX,t.clientY)},{passive:true});c.addEventListener('touchend',e=>end(e.changedTouches[0].clientX),{passive:true});c.addEventListener('mousedown',e=>start(e.clientX,e.clientY,'m'));window.addEventListener('mousemove',e=>{if(drag?.id==='m')move(e.clientX,e.clientY)});window.addEventListener('mouseup',e=>{if(drag?.id==='m')end(e.clientX)});}
function reset(c){c.style.transform='';c.querySelectorAll('.swipe-badge').forEach(x=>x.style.opacity=0)}
function acceptKnown(c){history.push({index,understood:[...understood]});c.style.transform='translateX(-120vw) rotate(-15deg)';c.style.opacity='0';showUndo('「知ってる」にしました');setTimeout(()=>{index++;renderDeck()},220)}
function openMore(c){c.style.transform='translateX(34px) rotate(5deg)';setTimeout(()=>{reset(c);openDetail()},130)}
function openDetail(){const d=cards[index];$('#detailPosition').textContent=`${index+1} / ${cards.length}`;$('#detailCountry').textContent=d.country;$('#detailTags').innerHTML=d.tags.map(t=>`<span class="tag">${t}</span>`).join('');$('#detailTitle').textContent=d.title;$('#detailDek').textContent=d.summary;$('#detailThree').textContent=d.summary;$('#detailWhat').textContent=d.what;$('#detailWhy').textContent=d.why;$('#detailWatch').textContent=d.watch;$('#detailSource').textContent=d.source;detail.classList.add('open');detail.setAttribute('aria-hidden','false')}
function closeDetail(){detail.classList.remove('open');detail.setAttribute('aria-hidden','true');understood.add(index);setTimeout(renderDeck,180)}
function undo(){const h=history.pop();if(!h)return;index=h.index;understood=new Set(h.understood);clear.classList.add('hidden');stage.classList.remove('hidden');renderDeck();$('#undoToast').classList.remove('show')}
function showUndo(t){$('#undoText').textContent=t;$('#undoToast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#undoToast').classList.remove('show'),4500)}
$('#startBatch').addEventListener('click',()=>{intro.classList.add('hidden');stage.classList.remove('hidden');renderDeck()});$('#detailBack').addEventListener('click',closeDetail);$('#undoBtn').addEventListener('click',undo);$('#undoTop').addEventListener('click',undo);detail.addEventListener('touchstart',e=>detailStartX=e.touches[0].clientX,{passive:true});detail.addEventListener('touchend',e=>{if(e.changedTouches[0].clientX-detailStartX<-70)closeDetail()},{passive:true});$('#batchCount').textContent=cards.length;$('#total').textContent=cards.length;if('serviceWorker' in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));}
