(()=>{
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const css=document.createElement('style');
css.textContent=`
.feed-tabs-hidden{display:none!important}.main{padding-top:8px}.topbar{grid-template-columns:74px 1fr 92px;height:74px}.brand-mark,.brand-word{cursor:pointer}.brand-mark{width:38px;height:38px}.geo-counter{position:absolute;right:18px;top:15px;min-width:64px;height:48px;justify-content:flex-end}.geo-digit{font-size:43px;min-width:29px;height:46px;animation:counterImpact .38s cubic-bezier(.16,.9,.25,1)}@keyframes counterImpact{0%{transform:scale(1.3) translateY(-5px) rotate(-2deg) skewX(-6deg);filter:blur(.7px)}38%{transform:scale(.92) translateY(3px) rotate(1deg) skewX(-6deg)}70%{transform:scale(1.04) translateY(-1px) skewX(-6deg)}100%{transform:scale(1) translateY(0) skewX(-6deg);filter:none}}
.top-tools{position:absolute;left:58px;top:18px;display:flex;gap:2px}.top-tool{width:34px;height:34px;border:0;background:transparent;color:var(--muted);display:grid;place-items:center;padding:7px}.top-tool svg{width:18px;height:18px;fill:none;stroke:currentColor;stroke-width:1.45;stroke-linecap:round;stroke-linejoin:round}
.card-title{font-size:28px;line-height:1.2;letter-spacing:-.035em;word-break:auto-phrase;line-break:strict;text-wrap:pretty;max-width:100%}.card-copy{top:24px}.card-summary{margin-top:2px}.news-card:before,.news-card:after{position:absolute;z-index:6;bottom:18px;color:rgba(255,255,255,.62);font-size:24px;font-weight:300;line-height:1;pointer-events:none;text-shadow:0 2px 12px rgba(0,0,0,.25)}.news-card:before{content:'←';left:19px}.news-card:after{content:'→';right:19px}
.bottom-nav{grid-template-columns:1.2fr .8fr 1.2fr;height:72px;padding:0 18px calc(env(safe-area-inset-bottom)*.35);gap:4px}.feed-nav{height:44px;border:0;background:transparent;color:var(--muted);font-size:10px;font-weight:780;letter-spacing:.11em;position:relative;border-radius:999px}.feed-nav.active{color:var(--ink);background:color-mix(in srgb,var(--jade) 10%,transparent)}.feed-nav.active:after{content:'';position:absolute;left:34%;right:34%;bottom:5px;height:2px;background:var(--jade);border-radius:2px}.feed-nav[data-feed-v2='hot'] i{position:absolute;width:4px;height:4px;border-radius:50%;background:#d37a62;right:19%;top:10px}
#cardsScreen{padding-bottom:10px}.deck{margin-top:2px;height:clamp(390px,calc(100dvh - 74px - 72px - 88px - env(safe-area-inset-bottom)),650px);min-height:390px}.action-dock{height:76px;margin-bottom:calc(78px + env(safe-area-inset-bottom));position:relative;z-index:2}@media(max-height:760px){.deck{min-height:360px;height:calc(100dvh - 292px)}.action-dock{height:64px}.action-circle{transform:scale(.9)}}
.detail-scroll{font-family:-apple-system,BlinkMacSystemFont,'Helvetica Neue','Noto Sans JP',sans-serif}.detail-body{padding-left:25px;padding-right:25px}.detail h1{font-family:inherit;font-size:34px;line-height:1.25;letter-spacing:-.035em;word-break:auto-phrase;line-break:strict;text-wrap:pretty}.detail-dek{font-family:inherit!important;font-size:16px!important;line-height:1.8!important;font-weight:560;color:var(--ink)!important}.article-copy{font-family:inherit!important}.article-copy p{font-family:inherit!important;font-size:16px!important;line-height:1.92!important;letter-spacing:.01em;color:color-mix(in srgb,var(--ink) 88%,var(--muted));margin:0 0 34px!important}.article-section-label{font-family:inherit;font-size:12px;line-height:1.3;letter-spacing:.08em;color:var(--jade);margin:36px 0 12px;padding-top:17px;border-top:1px solid var(--line);font-weight:820}.article-section-label:first-child{margin-top:26px}.detail-return-cue{margin:42px 0 20px;padding:22px 0;border-top:1px solid var(--line);display:flex;align-items:center;gap:14px;color:var(--muted)}.detail-return-cue b{font-size:30px;font-weight:300;color:var(--jade);animation:returnNudge 1.8s ease-in-out infinite}.detail-return-cue span{font-size:11px;letter-spacing:.04em}@keyframes returnNudge{0%,100%{transform:translateX(5px);opacity:.45}50%{transform:translateX(-5px);opacity:1}}
.topic-fallback{position:absolute;inset:0;overflow:hidden;background:linear-gradient(145deg,#063d48,#0b8f99 58%,#87c7c4);display:grid;place-items:center}.topic-fallback i{position:absolute;width:70%;height:70%;clip-path:polygon(50% 0,100% 100%,0 100%);background:rgba(255,255,255,.08)}.topic-fallback i:nth-child(1){left:-18%;top:-8%;transform:rotate(22deg)}.topic-fallback i:nth-child(2){right:-22%;bottom:-8%;transform:rotate(-18deg);background:rgba(3,31,37,.22)}.topic-fallback i:nth-child(3){left:25%;top:28%;transform:rotate(88deg);background:rgba(213,160,137,.10)}.topic-fallback span{z-index:2;color:rgba(255,255,255,.78);font-size:10px;letter-spacing:.24em;font-weight:800}
.tutorial{padding:0}.tutorial-v2{position:relative;width:100%;height:100%;display:grid;place-items:center}.tutorial-mini-card{width:min(64vw,300px);height:min(50vh,440px);border-radius:30px;background:linear-gradient(165deg,#073b43,#0b8f99 65%,#85c8c5);box-shadow:var(--shadow);padding:25px;color:white;display:flex;flex-direction:column;justify-content:flex-start}.tutorial-mini-card span{font-size:9px;letter-spacing:.22em;opacity:.72}.tutorial-mini-card strong{margin-top:14px;font-size:24px;line-height:1.25;letter-spacing:-.03em}.tutorial-gesture{position:absolute;display:flex;align-items:center;gap:8px;color:var(--ink)}.tutorial-gesture b{font-size:29px;font-weight:300;color:var(--jade)}.tutorial-gesture span{font-size:11px;font-weight:720}.tg-left{left:5vw;top:50%}.tg-right{right:5vw;top:50%}.tg-up{left:50%;top:8%;transform:translateX(-50%);flex-direction:column;gap:2px}.tutorial-start{position:absolute;bottom:calc(28px + env(safe-area-inset-bottom));left:50%;transform:translateX(-50%);border:1px solid var(--line);background:var(--surface);color:var(--ink);border-radius:999px;padding:12px 24px;font-size:12px;font-weight:750}
/* KAWASEMI canyon launch v3 */
.splash{background:#063f46!important;perspective:900px}.splash-photo{background-image:linear-gradient(180deg,rgba(0,20,23,.03),rgba(0,30,34,.03) 48%,rgba(0,42,46,.18) 100%),url('https://thenomad.life/wp-content/uploads/2022/10/Slovenie0000.jpg')!important;background-position:center 52%!important;background-size:cover!important;transform:scale(1.055);transition:none!important;will-change:transform,filter}.splash-brand{display:none}.splash-far-polygons{inset:0;opacity:0!important;mix-blend-mode:normal;background:linear-gradient(180deg,rgba(4,93,99,0),rgba(4,93,99,.06) 40%,rgba(5,104,110,.18));transition:opacity .3s ease!important}.splash-far-polygons i{opacity:.7}.flight-guide{bottom:calc(145px + env(safe-area-inset-bottom));height:42vh}.flight-guide span{width:2px;background:linear-gradient(180deg,transparent,rgba(255,255,255,.74) 55%,rgba(255,255,255,.15))}.splash-bird{bottom:calc(42px + env(safe-area-inset-bottom));width:64px;height:60px;transition:none!important;transform-origin:50% 65%;filter:drop-shadow(0 10px 15px rgba(0,0,0,.24))}.splash:before{content:'';position:absolute;z-index:7;left:50%;top:54%;width:16px;height:6px;border:2px solid rgba(218,255,252,0);border-radius:50%;transform:translate(-50%,-50%) scale(.2);pointer-events:none}.splash.kawa-flight .flight-guide{opacity:0;transition:opacity .18s}.splash.kawa-flight .splash-bird{animation:kawaLaunch 1.48s cubic-bezier(.12,.72,.08,1) forwards!important}.splash.kawa-flight .splash-photo{animation:canyonRush 1.48s cubic-bezier(.12,.72,.08,1) forwards!important}.splash.kawa-flight .splash-far-polygons{animation:polygonWorld 1.48s ease forwards!important}.splash.kawa-flight:before{animation:waterImpact 1.48s ease forwards}
@keyframes kawaLaunch{0%{transform:translateX(-50%) translateY(var(--held-y,0px)) scale(1);opacity:1}10%{transform:translateX(-50%) translateY(calc(var(--held-y,0px) + 7px)) scale(1.03);opacity:1}24%{transform:translateX(-50%) translateY(-9vh) scale(.82);opacity:1}53%{transform:translateX(-50%) translateY(-47vh) scale(.31);opacity:1}70%{transform:translateX(-50%) translateY(-57vh) scale(.16) rotate(0deg);opacity:1}82%{transform:translateX(-50%) translateY(-48vh) scale(.095) rotate(180deg);opacity:1}91%{transform:translateX(-50%) translateY(-39vh) scale(.055) rotate(180deg);opacity:.95}100%{transform:translateX(-50%) translateY(-36vh) scale(.025) rotate(180deg);opacity:0}}
@keyframes canyonRush{0%,12%{transform:scale(1.055);filter:saturate(1.05)}55%{transform:scale(1.13);filter:saturate(1.16)}82%{transform:scale(1.23) translateY(-1.5%);filter:saturate(1.25) blur(.2px)}100%{transform:scale(1.34) translateY(-3%);filter:saturate(1.35) blur(1.2px)}}
@keyframes polygonWorld{0%,60%{opacity:0}78%{opacity:.12}100%{opacity:1}}
@keyframes waterImpact{0%,84%{border-color:rgba(218,255,252,0);transform:translate(-50%,-50%) scale(.2);opacity:0}90%{border-color:rgba(218,255,252,.85);opacity:1}100%{border-color:rgba(218,255,252,0);transform:translate(-50%,-50%) scale(18);opacity:0}}
.splash.kawa-exit{opacity:0;transition:opacity .34s ease .02s!important;pointer-events:none}
`;
document.head.appendChild(css);

const tutorial=$('#tutorial');if(tutorial){tutorial.innerHTML=`<div class="tutorial-v2"><div class="tutorial-mini-card"><span>KAWASEMI</span><strong>一枚ずつ、世界へ。</strong></div><div class="tutorial-gesture tg-left"><b>←</b><span>知ってる</span></div><div class="tutorial-gesture tg-up"><b>↑</b><span>あとで読む</span></div><div class="tutorial-gesture tg-right"><span>記事を読む</span><b>→</b></div><button id="tutorialDoneV2" class="tutorial-start">はじめる</button></div>`;$('#tutorialDoneV2')?.addEventListener('click',finishTutorial)}
const oldNav=$('.bottom-nav');if(oldNav){oldNav.innerHTML=`<button class="feed-nav active" data-feed-v2="forYou">FOR YOU</button><button class="feed-nav" data-feed-v2="hot">HOT<i></i></button><button class="feed-nav" data-feed-v2="must">MUST</button>`;$$('.feed-nav').forEach(b=>b.addEventListener('click',()=>{switchScreen('cardsScreen');switchFeed(b.dataset.feedV2);$$('.feed-nav').forEach(x=>x.classList.toggle('active',x===b))}))}$('.feed-tabs')?.classList.add('feed-tabs-hidden');
const topbar=$('.topbar');if(topbar&&!$('.top-tools')){const tools=document.createElement('div');tools.className='top-tools';tools.innerHTML=`<button class="top-tool" data-go="savedScreen" aria-label="保存"><svg viewBox="0 0 24 24"><path d="M7 3h10v18l-5-3.5L7 21z"/></svg></button><button class="top-tool" data-go="meScreen" aria-label="設定"><svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="3"/><path d="M12 2v3M12 19v3M2 12h3M19 12h3M5 5l2 2M17 17l2 2M19 5l-2 2M7 17l-2 2"/></svg></button>`;topbar.appendChild(tools);$$('.top-tool',tools).forEach(b=>b.addEventListener('click',()=>switchScreen(b.dataset.go)))}
['.brand-mark','.brand-word'].forEach(sel=>{const el=$(sel);if(!el)return;el.setAttribute('role','button');el.setAttribute('tabindex','0');const home=()=>{switchScreen('cardsScreen');switchFeed('forYou');$$('.feed-nav').forEach(x=>x.classList.toggle('active',x.dataset.feedV2==='forYou'))};el.addEventListener('click',home);el.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' ')home()})});
const detail=$('#detail'),scroll=$('.detail-scroll',detail),box=$('#detailArticle');new MutationObserver(()=>{if(detail.classList.contains('open')){scroll.scrollTop=0;requestAnimationFrame(()=>scroll.scrollTop=0)}}).observe(detail,{attributes:true,attributeFilter:['class']});
new MutationObserver(()=>{const labels=['何が起きている？','なぜ重要？','背景','これから'];$$('p',box).forEach((p,i)=>{if(p.previousElementSibling?.classList.contains('article-section-label'))return;const h=document.createElement('h2');h.className='article-section-label';h.textContent=labels[i]||'ポイント';p.before(h)});if(!$('.detail-return-cue',$('.detail-body'))){const cue=document.createElement('div');cue.className='detail-return-cue';cue.innerHTML='<b>←</b><span>左へスワイプしてカードへ戻る</span>';$('#detailSource')?.after(cue)}}).observe(box,{childList:true});
let back=null;scroll.addEventListener('touchstart',e=>{const t=e.touches[0];back={x:t.clientX,y:t.clientY,axis:null}},{capture:true,passive:true});scroll.addEventListener('touchmove',e=>{if(!back||!detail.classList.contains('open'))return;const t=e.touches[0],dx=t.clientX-back.x,dy=t.clientY-back.y;if(!back.axis&&(Math.abs(dx)>9||Math.abs(dy)>9))back.axis=Math.abs(dx)>Math.abs(dy)?'x':'y';if(back.axis==='x'&&dx<0)detail.style.setProperty('transform',`translateX(${dx}px) scale(${1-Math.min(.025,Math.abs(dx)/7000)})`,'important')},{capture:true,passive:true});scroll.addEventListener('touchend',e=>{if(!back)return;const t=e.changedTouches[0],dx=t.clientX-back.x,axis=back.axis;back=null;detail.style.removeProperty('transform');if(axis==='x'&&dx<-78)closeDetail(false)},{capture:true,passive:true});
function fallback(root=document){$$('img',root).forEach(img=>{if(img.dataset.fb)return;img.dataset.fb='1';img.addEventListener('error',()=>{const host=img.parentElement;if(!host)return;const a=state.detailArticle||articleById(img.closest('[data-id]')?.dataset.id);host.innerHTML=`<div class="topic-fallback"><i></i><i></i><i></i><span>${(a?.tags?.[0]||'WORLD').toUpperCase()}</span></div>`},{once:true})})}new MutationObserver(m=>m.forEach(x=>x.addedNodes.forEach(n=>{if(n.nodeType===1)fallback(n)}))).observe(document.body,{childList:true,subtree:true});fallback();
document.addEventListener('click',()=>requestAnimationFrame(()=>$$('.feed-nav').forEach(x=>x.classList.toggle('active',x.dataset.feedV2===state.feed))));

/* Heavy, sticky launch: capture events so the older splash handler never fights this one. */
const splash=$('#splash'),bird=$('#splashBird'),photo=$('.splash-photo');let flight=null,launched=false;
function sbegin(y,t){if(launched)return;flight={y,lastY:y,lastT:t,dy:0,v:0};bird.style.transition='none';}
function smove(y,t){if(!flight||launched)return;const raw=Math.min(0,y-flight.y),dist=Math.abs(raw);flight.v=(flight.lastY-y)/Math.max(1,t-flight.lastT);flight.lastY=y;flight.lastT=t;flight.dy=raw;const sticky=dist<95?dist*.28:26.6+(dist-95)*.62;const p=Math.min(1,dist/300);bird.style.transform=`translateX(-50%) translateY(${-sticky}px) scale(${1-p*.18})`;photo.style.transform=`scale(${1.055+p*.018})`;}
function slaunch(){if(launched)return;launched=true;const current=bird.style.transform.match(/translateY\((-?[\d.]+)px\)/);bird.style.setProperty('--held-y',`${current?Number(current[1]):0}px`);bird.style.transform='';photo.style.transform='';splash.classList.add('kawa-flight');setTimeout(()=>splash.classList.add('kawa-exit'),1280);setTimeout(()=>{splash.classList.add('hidden');showAppAfterSplash()},1640)}
function send(y,t){if(!flight||launched)return;const dist=Math.abs(Math.min(0,y-flight.y)),velocity=flight.v;flight=null;if(dist>72||velocity>.45)return slaunch();bird.style.transition='transform .5s cubic-bezier(.18,.9,.2,1)';photo.style.transition='transform .5s cubic-bezier(.18,.9,.2,1)';bird.style.transform='';photo.style.transform='scale(1.055)';setTimeout(()=>{bird.style.transition='none';photo.style.transition='none'},520)}
['touchstart','touchmove','touchend'].forEach(type=>splash?.addEventListener(type,e=>{if(launched)return;e.stopImmediatePropagation();const t=(type==='touchend'?e.changedTouches[0]:e.touches[0]),now=performance.now();if(type==='touchstart')sbegin(t.clientY,now);else if(type==='touchmove')smove(t.clientY,now);else send(t.clientY,now)},{capture:true,passive:true}));
splash?.addEventListener('pointerdown',e=>{if(e.pointerType==='touch'||launched)return;e.stopImmediatePropagation();sbegin(e.clientY,performance.now());splash.setPointerCapture?.(e.pointerId)},{capture:true});splash?.addEventListener('pointermove',e=>{if(e.pointerType==='touch'||!flight||launched)return;e.stopImmediatePropagation();smove(e.clientY,performance.now())},{capture:true});splash?.addEventListener('pointerup',e=>{if(e.pointerType==='touch'||!flight||launched)return;e.stopImmediatePropagation();send(e.clientY,performance.now())},{capture:true});
})();