const trashSVG="<svg viewBox=\"0 0 24 24\" aria-hidden=\"true\"><path d=\"M5 7h14M9 7V5h6v2M8 9l.7 9h6.6L16 9\"/></svg>";
const photos=[
{src:BM_PHOTOS[0],size:"1.2 MB",date:"2026年8月16日 09:41",place:""},
{src:BM_PHOTOS[1],size:"820 KB",date:"2026年8月16日 09:38",place:""},
{src:BM_PHOTOS[2],size:"3.8 MB",date:"2026年8月16日 09:33",place:""},
{src:BM_PHOTOS[3],size:"2.1 MB",date:"2026年8月16日 09:27",place:""},
{src:BM_PHOTOS[4],size:"5.4 MB",date:"2026年8月15日 17:04",place:""}
];
const film=document.getElementById("film"),counter=document.getElementById("counter"),trashTarget=document.getElementById("trashTarget");
const viewer=document.getElementById("viewer"),viewerImg=document.getElementById("viewerImg"),viewerSize=document.getElementById("viewerSize");
const backdrop=document.getElementById("backdrop"),sheet=document.getElementById("sheet"),detailDate=document.getElementById("detailDate"),detailPlace=document.getElementById("detailPlace"),neighbors=document.getElementById("neighbors");
const queued=new Set();let current=0;
function signal(){return '<span class="signal" aria-hidden="true"><i></i><i></i><i></i></span>'}
function render(){film.innerHTML="";photos.forEach((p,i)=>{if(queued.has(i))return;const card=document.createElement("article");card.className="photo-card";card.dataset.i=i;card.innerHTML=`<img class="photo-media" src="${p.src}" alt=""><div class="size-badge">${signal()}${p.size}</div>`;film.appendChild(card);wire(card)});requestAnimationFrame(updateCounter);updateReview()}
function visibleCards(){return[...film.querySelectorAll(".photo-card")]}
function nearest(){const cards=visibleCards();if(!cards.length)return null;const cx=innerWidth/2;return cards.reduce((best,c)=>{const r=c.getBoundingClientRect(),d=Math.abs((r.left+r.right)/2-cx);return!best||d<best.d?{c,d}:best},null).c}
function updateCounter(){const c=nearest();if(!c){counter.textContent=`${photos.length} / ${photos.length}`;return}current=Number(c.dataset.i);counter.textContent=`${current+1} / ${photos.length}`}
film.addEventListener("scroll",()=>requestAnimationFrame(updateCounter),{passive:true});
function vibrate(){if(navigator.vibrate)navigator.vibrate(6)}
function resisted(d){if(d<=0)return d*.16;if(d<180)return d*.82;return 147.6+(d-180)*.35}
function restore(card,x,y,rot=0){const a=card.animate([{transform:card.style.transform||`translate3d(${x}px,${y}px,0) rotate(${rot}deg)`},{transform:"translate3d(0,3px,0) scale(.999)"},{transform:"translate3d(0,0,0) scale(1)"}],{duration:135,easing:"cubic-bezier(.20,.78,.18,1)"});a.onfinish=()=>{card.style.transform="";card.style.opacity="";trashTarget.classList.remove("hot")}}
function queuePhoto(card){const i=Number(card.dataset.i);if(queued.has(i))return;queued.add(i);vibrate();card.style.pointerEvents="none";setTimeout(()=>render(),0)}
function directLaunch(card,dx,dy,vy){const distance=Math.max(innerHeight*.95,720);trashTarget.classList.add("hot");vibrate();const anim=card.animate([{transform:card.style.transform||"translate3d(0,0,0)",opacity:1},{transform:`translate3d(${dx*.18}px,-${distance}px,0) scale(.96) rotate(${Math.max(-5,Math.min(5,dx/35))}deg)`,opacity:.02}],{duration:Math.abs(vy)>.6?95:125,easing:"cubic-bezier(.12,.82,.16,1)",fill:"forwards"});anim.onfinish=()=>{trashTarget.classList.remove("hot");queuePhoto(card)}}
function slingshotLaunch(card,x,y,vx,vy){trashTarget.classList.add("hot");vibrate();let px=x,py=y,svx=vx*.18,svy=Math.max(-120,vy*.18),last=performance.now(),detached=false,raf=0;const k=105,c=12.5;function tick(t){let dt=Math.min(.022,(t-last)/1000)*2;last=t;if(!detached){const ax=-k*px-c*svx,ay=-k*py-c*svy;svx+=ax*dt;svy+=ay*dt;px+=svx*dt;py+=svy*dt;if(py<=0&&svy<0){detached=true;const bonus=(420+Math.max(0,y)*4.9)*2;svy=Math.min(svy,-bonus);svx+=-x*2.7}}else{svy-=220*dt;svx*=Math.pow(.992,dt*60);px+=svx*dt;py+=svy*dt}const away=Math.max(0,-py),scale=1-Math.min(.13,away/innerHeight*.12),opacity=1-Math.min(.86,Math.max(0,away-innerHeight*.22)/(innerHeight*.62));card.style.transform=`translate3d(${px}px,${py}px,0) scale(${scale}) rotate(${Math.max(-6,Math.min(6,px/34))}deg)`;card.style.opacity=opacity;if(py<-card.offsetHeight-100||opacity<.06){cancelAnimationFrame(raf);trashTarget.classList.remove("hot");queuePhoto(card);return}raf=requestAnimationFrame(tick)}raf=requestAnimationFrame(tick)}
function wire(card){let sx=0,sy=0,lx=0,ly=0,lastT=0,vx=0,vy=0,mode="pending",moved=false,long=false,longTimer=null,x=0,y=0;
card.addEventListener("pointerdown",e=>{if(e.pointerType==="mouse"&&e.button!==0)return;sx=lx=e.clientX;sy=ly=e.clientY;lastT=performance.now();vx=vy=0;mode="pending";moved=false;long=false;x=y=0;longTimer=setTimeout(()=>{if(!moved){long=true;openDetails(Number(card.dataset.i))}},520)});
card.addEventListener("pointermove",e=>{const now=performance.now(),dt=Math.max(8,now-lastT),dx=e.clientX-sx,dy=e.clientY-sy,adx=Math.abs(dx),ady=Math.abs(dy);vx=(e.clientX-lx)/dt*1000;vy=(e.clientY-ly)/dt*1000;lx=e.clientX;ly=e.clientY;lastT=now;if(adx>6||ady>6){moved=true;clearTimeout(longTimer)}if(mode==="pending"&&(adx>8||ady>8))mode=ady>adx*1.06?"vertical":"horizontal";if(mode!=="vertical")return;if(dy>0){x=resisted(dx*.38);y=resisted(dy);const scale=1+Math.min(.03,y/6500),rot=Math.max(-4,Math.min(4,x/28));card.style.transform=`translate3d(${x}px,${y}px,0) scale(${scale}) rotate(${rot}deg)`;card.style.opacity="1";if(y>38)trashTarget.classList.add("hot");else trashTarget.classList.remove("hot")}else if(dy<0){x=dx*.05;y=dy*.9;card.style.transform=`translate3d(${x}px,${y}px,0)`;if(dy<-28)trashTarget.classList.add("hot")}});
const finish=e=>{clearTimeout(longTimer);const dx=(e.clientX??lx)-sx,dy=(e.clientY??ly)-sy;if(long){card.style.transform="";trashTarget.classList.remove("hot");return}if(mode==="vertical"){if(dy>38){slingshotLaunch(card,x,y,vx,vy);return}if(dy<-42||(dy<-16&&vy<-.28)){directLaunch(card,dx,dy,vy);return}restore(card,x,y,Math.max(-4,Math.min(4,x/28)));return}card.style.transform="";trashTarget.classList.remove("hot");if(!moved&&Math.abs(dx)<8&&Math.abs(dy)<8)openViewer(Number(card.dataset.i))};
card.addEventListener("pointerup",finish);card.addEventListener("pointercancel",()=>{clearTimeout(longTimer);restore(card,x,y)})}
function updateReview(){const count=queued.size;const bytes=[1.2,.82,3.8,2.1,5.4].reduce((sum,v,i)=>sum+(queued.has(i)?v:0),0);const p=document.getElementById("photoReviewCount"),sz=document.getElementById("photoReviewSize"),total=document.getElementById("totalSize"),summary=document.getElementById("finalSummary");if(p)p.textContent=`${count}枚`;if(sz)sz.textContent=bytes>=1?`${bytes.toFixed(bytes<10?1:0)} MB`:`${Math.round(bytes*1024)} KB`;const appGB=appQueued?1.8:0;const totalGB=appGB+bytes/1024;if(total)total.textContent=totalGB>=1?`${totalGB.toFixed(2)} GB`:`${Math.max(0,Math.round(bytes))} MB`;if(summary)summary.textContent=`写真・動画 ${count}枚${appQueued?"　·　アプリ 1個":""}`}
function openViewer(i){const p=photos[i];viewerImg.src=p.src;viewerSize.innerHTML=signal()+p.size;viewer.classList.add("show")} function closeViewer(){viewer.classList.remove("show")} document.getElementById("viewerClose").addEventListener("click",closeViewer);
function openDetails(i){const p=photos[i];detailDate.textContent=p.date;detailPlace.textContent=p.place||"";neighbors.innerHTML="";[i-2,i-1,i,i+1,i+2].filter(x=>x>=0&&x<photos.length).forEach(x=>{const im=document.createElement("img");im.className="neighbor";im.src=photos[x].src;im.alt="";neighbors.appendChild(im)});backdrop.classList.add("show");sheet.classList.add("show")} function closeDetails(){backdrop.classList.remove("show");sheet.classList.remove("show")} backdrop.addEventListener("click",closeDetails);
const appCard=document.getElementById("appCard");let asy=0,ast=0,appDrag=false,appQueued=false;
appCard.addEventListener("pointerdown",e=>{asy=e.clientY;ast=performance.now();appDrag=false;appCard.setPointerCapture?.(e.pointerId)});
appCard.addEventListener("pointermove",e=>{const dy=e.clientY-asy;if(dy<-8){appDrag=true;appCard.style.transform=`translate3d(0,${dy*.9}px,0)`;appCard.style.opacity=String(Math.max(.55,1+dy/520))}});
appCard.addEventListener("pointerup",e=>{const dy=e.clientY-asy,vy=dy/Math.max(16,performance.now()-ast);if(appDrag&&(dy<-40||(dy<-16&&vy<-.26))){appQueued=true;vibrate();appCard.animate([{transform:appCard.style.transform,opacity:appCard.style.opacity||1},{transform:"translate3d(0,-100vh,0) scale(.96)",opacity:0}],{duration:110,easing:"cubic-bezier(.12,.82,.16,1)",fill:"forwards"}).onfinish=()=>{appCard.style.visibility="hidden";updateReview()}}else{appCard.animate([{transform:appCard.style.transform||"none",opacity:appCard.style.opacity||1},{transform:"none",opacity:1}],{duration:130,easing:"cubic-bezier(.2,.78,.18,1)"}).onfinish=()=>{appCard.style.transform="";appCard.style.opacity=""}}});
const screens={photos:document.getElementById("photosScreen"),apps:document.getElementById("appsScreen"),final:document.getElementById("finalScreen")};
function go(name){Object.entries(screens).forEach(([k,s])=>s.classList.toggle("active",k===name));document.querySelectorAll(".nav-btn").forEach(b=>b.classList.toggle("active",b.dataset.target===name))}
document.querySelectorAll(".nav-btn").forEach(b=>b.addEventListener("click",()=>go(b.dataset.target)));document.getElementById("topReview").addEventListener("click",()=>go("final"));document.getElementById("cancelBtn").addEventListener("click",()=>go("photos"));document.getElementById("deleteBtn").addEventListener("click",()=>alert("プロトタイプでは実際の写真やアプリは削除されません。"));
render();