const trashSVG="<svg viewBox=\"0 0 24 24\" aria-hidden=\"true\"><path d=\"M5 7h14M9 7V5h6v2M8 9l.7 9h6.6L16 9\"/></svg>";
const capcutSVG='<svg viewBox="0 0 64 64" aria-hidden="true"><path d="M12 18h40L18 46h34M12 46h40L18 18h34" fill="none" stroke="#111" stroke-linecap="round" stroke-linejoin="round" stroke-width="5.5"></path></svg>';
const photos=[
{src:BM_PHOTOS[0],size:"1.2 MB",date:"2026年8月16日 09:41",place:""},
{src:BM_PHOTOS[1],size:"820 KB",date:"2026年8月16日 09:38",place:""},
{src:BM_PHOTOS[2],size:"3.8 MB",date:"2026年8月16日 09:33",place:""},
{src:BM_PHOTOS[3],size:"2.1 MB",date:"2026年8月16日 09:27",place:""},
{src:BM_PHOTOS[4],size:"5.4 MB",date:"2026年8月15日 17:04",place:""}
];
const film=document.getElementById("film"),counter=document.getElementById("counter"),trashTarget=document.getElementById("trashTarget");
const viewer=document.getElementById("viewer"),viewerImg=document.getElementById("viewerImg"),viewerSize=document.getElementById("viewerSize");
const backdrop=document.getElementById("backdrop"),sheet=document.getElementById("sheet"),detailDate=document.getElementById("detailDate"),detailPlace=document.getElementById("detailPlace"),neighbors=document.getElementById("neighbors");
const deleteBackdrop=document.getElementById("deleteBackdrop"),deleteSheet=document.getElementById("deleteSheet"),deleteSheetBody=document.getElementById("deleteSheetBody");
const queued=new Set();let current=0,appQueued=false,appHintShown=false;
function signal(){return '<span class="signal" aria-hidden="true"><i></i><i></i><i></i></span>'}
function render(){film.innerHTML="";photos.forEach((p,i)=>{if(queued.has(i))return;const card=document.createElement("article");card.className="photo-card";card.dataset.i=i;card.innerHTML=`<img class="photo-media" src="${p.src}" alt=""><div class="size-badge">${signal()}${p.size}</div>`;film.appendChild(card);wire(card)});requestAnimationFrame(updateCounter);updateReview()}
function visibleCards(){return[...film.querySelectorAll(".photo-card")]}
function nearest(){const cards=visibleCards();if(!cards.length)return null;const cx=innerWidth/2;return cards.reduce((best,c)=>{const r=c.getBoundingClientRect(),d=Math.abs((r.left+r.right)/2-cx);return!best||d<best.d?{c,d}:best},null).c}
function updateCounter(){const c=nearest();if(!c){counter.textContent=`${photos.length} / ${photos.length}`;return}current=Number(c.dataset.i);counter.textContent=`${current+1} / ${photos.length}`}
film.addEventListener("scroll",()=>requestAnimationFrame(updateCounter),{passive:true});
function vibrate(){if(navigator.vibrate)navigator.vibrate(6)}
function resisted(d){if(d<=0)return d*.16;if(d<180)return d*.82;return 147.6+(d-180)*.35}
function restore(card,x,y,rot=0){const a=card.animate([{transform:card.style.transform||`translate3d(${x}px,${y}px,0) rotate(${rot}deg)`},{transform:"translate3d(0,3px,0) scale(.999)"},{transform:"translate3d(0,0,0) scale(1)"}],{duration:135,easing:"cubic-bezier(.20,.78,.18,1)"});a.onfinish=()=>{card.style.transform="";card.style.opacity="";trashTarget.classList.remove("hot")}}
function queuePhoto(card){const i=Number(card.dataset.i);if(queued.has(i))return;queued.add(i);vibrate();card.style.pointerEvents="none";setTimeout(()=>render(),0)}
function directLaunch(card,dx,dy,vy){const distance=Math.max(innerHeight*.95,720);trashTarget.classList.add("hot");vibrate();const anim=card.animate([{transform:card.style.transform||"translate3d(0,0,0)",opacity:1},{transform:`translate3d(${dx*.18}px,-${distance}px,0) scale(.96) rotate(${Math.max(-5,Math.min(5,dx/35))}deg)`,opacity:.02}],{duration:Math.abs(vy)>.6?95:125,easing:"cubic-bezier(.12,.82,.16,1)",fill:"forwards"});anim.onfinish=()=>{trashTarget.classList.remove("hot");queuePhoto(card)}}
function slingshotLaunch(card,x,y,vx,vy){trashTarget.classList.add("hot");vibrate();let px=x,py=y,svx=vx*.18,svy=Math.max(-120,vy*.18),last=performance.now(),detached=false,raf=0;const k=105,c=12.5;function tick(t){let dt=Math.min(.022,(t-last)/1000)*2;last=t;if(!detached){const ax=-k*px-c*svx,ay=-k*py-c*svy;svx+=ax*dt;svy+=ay*dt;px+=svx*dt;py+=svy*dt;if(py<=0&&svy<0){detached=true;const bonus=(420+Math.max(0,y)*4.9)*2;svy=Math.min(svy,-bonus);svx+=-x*2.7}}else{svy-=220*dt;svx*=Math.pow(.992,dt*60);px+=svx*dt;py+=svy*dt}const away=Math.max(0,-py),scale=1-Math.min(.13,away/innerHeight*.12),opacity=1-Math.min(.86,Math.max(0,away-innerHeight*.22)/(innerHeight*.62));card.style.transform=`translate3d(${px}px,${py}px,0) scale(${scale}) rotate(${Math.max(-6,Math.min(6,px/34))}deg)`;card.style.opacity=opacity;if(py<-card.offsetHeight-100||opacity<.06){cancelAnimationFrame(raf);trashTarget.classList.remove("hot");queuePhoto(card);return}raf=requestAnimationFrame(tick)}raf=requestAnimationFrame(tick)}
function wire(card){let sx=0,sy=0,lx=0,ly=0,lastT=0,vx=0,vy=0,mode="pending",moved=false,long=false,longTimer=null,x=0,y=0;
card.addEventListener("pointerdown",e=>{if(e.pointerType==="mouse"&&e.button!==0)return;sx=lx=e.clientX;sy=ly=e.clientY;lastT=performance.now();vx=vy=0;mode="pending";moved=false;long=false;x=y=0;longTimer=setTimeout(()=>{if(!moved){long=true;openDetails(Number(card.dataset.i))}},520)});
card.addEventListener("pointermove",e=>{const now=performance.now(),dt=Math.max(8,now-lastT),dx=e.clientX-sx,dy=e.clientY-sy,adx=Math.abs(dx),ady=Math.abs(dy);vx=(e.clientX-lx)/dt*1000;vy=(e.clientY-ly)/dt*1000;lx=e.clientX;ly=e.clientY;lastT=now;if(adx>6||ady>6){moved=true;clearTimeout(longTimer)}if(mode==="pending"&&(adx>8||ady>8))mode=ady>adx*1.06?"vertical":"horizontal";if(mode!=="vertical")return;if(dy>0){x=resisted(dx*.38);y=resisted(dy);const scale=1+Math.min(.03,y/6500),rot=Math.max(-4,Math.min(4,x/28));card.style.transform=`translate3d(${x}px,${y}px,0) scale(${scale}) rotate(${rot}deg)`;card.style.opacity="1";if(y>38)trashTarget.classList.add("hot");else trashTarget.classList.remove("hot")}else if(dy<0){x=dx*.05;y=dy*.9;card.style.transform=`translate3d(${x}px,${y}px,0)`;if(dy<-28)trashTarget.classList.add("hot")}});
const finish=e=>{clearTimeout(longTimer);const dx=(e.clientX??lx)-sx,dy=(e.clientY??ly)-sy;if(long){card.style.transform="";trashTarget.classList.remove("hot");return}if(mode==="vertical"){if(dy>38){slingshotLaunch(card,x,y,vx,vy);return}if(dy<-42||(dy<-16&&vy<-.28)){directLaunch(card,dx,dy,vy);return}restore(card,x,y,Math.max(-4,Math.min(4,x/28)));return}card.style.transform="";trashTarget.classList.remove("hot");if(!moved&&Math.abs(dx)<8&&Math.abs(dy)<8)openViewer(Number(card.dataset.i))};
card.addEventListener("pointerup",finish);card.addEventListener("pointercancel",()=>{clearTimeout(longTimer);restore(card,x,y)})}
function updateReview(){const count=queued.size;const bytes=[1.2,.82,3.8,2.1,5.4].reduce((sum,v,i)=>sum+(queued.has(i)?v:0),0);const p=document.getElementById("photoReviewCount"),sz=document.getElementById("photoReviewSize"),total=document.getElementById("totalSize"),summary=document.getElementById("finalSummary"),photoRow=document.getElementById("photoReviewRow"),appRow=document.getElementById("appReviewRow"),t1=document.getElementById("reviewThumb1"),t2=document.getElementById("reviewThumb2"),deleteBtn=document.getElementById("deleteBtn");if(p)p.textContent=`${count}枚`;if(sz)sz.textContent=bytes>=1?`${bytes.toFixed(bytes<10?1:0)} MB`:`${Math.round(bytes*1024)} KB`;if(photoRow)photoRow.style.display=count?"grid":"none";const q=[...queued];if(t1&&q.length){t1.src=photos[q[0]].src;t1.style.display=""}else if(t1)t1.style.display="none";if(t2&&q.length>1){t2.src=photos[q[1]].src;t2.style.display=""}else if(t2)t2.style.display="none";if(appRow)appRow.style.display=appQueued?"grid":"none";const appGB=appQueued?1.8:0;const totalGB=appGB+bytes/1024;if(total)total.textContent=totalGB>=1?`${totalGB.toFixed(2)} GB`:`${Math.max(0,Math.round(bytes))} MB`;if(summary)summary.textContent=`写真・動画 ${count}枚${appQueued?"　·　アプリ 1個":""}`;if(deleteBtn){deleteBtn.disabled=!count&&!appQueued;deleteBtn.textContent=count&&appQueued?"削除を進める":count?"写真・動画を削除":"CapCutを削除"}}
function openViewer(i){const p=photos[i];viewerImg.src=p.src;viewerSize.innerHTML=signal()+p.size;viewer.classList.add("show")}function closeViewer(){viewer.classList.remove("show")}document.getElementById("viewerClose").addEventListener("click",closeViewer);
function openDetails(i){const p=photos[i];detailDate.textContent=p.date;detailPlace.textContent=p.place||"";neighbors.innerHTML="";[i-2,i-1,i,i+1,i+2].filter(x=>x>=0&&x<photos.length).forEach(x=>{const im=document.createElement("img");im.className="neighbor";im.src=photos[x].src;im.alt="";neighbors.appendChild(im)});backdrop.classList.add("show");sheet.classList.add("show")}function closeDetails(){backdrop.classList.remove("show");sheet.classList.remove("show")}backdrop.addEventListener("click",closeDetails);
function openDeleteSheet(html){deleteSheetBody.innerHTML=html;deleteBackdrop.classList.add("show");deleteSheet.classList.add("show")}
function closeDeleteSheet(){deleteBackdrop.classList.remove("show");deleteSheet.classList.remove("show")}
deleteBackdrop.addEventListener("click",closeDeleteSheet);
function appHead(sub="iPhoneで削除"){return `<div class="delete-sheet-head"><div class="delete-app-icon">${capcutSVG}</div><div><div class="delete-sheet-title">CapCut</div><div class="delete-sheet-sub">${sub}</div></div></div>`}
function showAppQueuedHint(){if(appHintShown)return;appHintShown=true;openDeleteSheet(`${appHead("削除候補に追加しました")}<p class="delete-sheet-note">CapCut本体はbe minimalから直接消せないため、最後にiPhone側で削除します。</p><button class="delete-sheet-primary" id="hintOK">OK</button>`);document.getElementById("hintOK").onclick=closeDeleteSheet}
function showAppDeleteGuide(afterPhotos=false){openDeleteSheet(`${appHead()}${afterPhotos?'<p class="delete-sheet-note delete-done">写真・動画の削除は完了。続けてCapCutを削除します。</p>':''}<div class="delete-instructions"><div class="delete-instruction"><span class="delete-step">1</span><span>ホーム画面でCapCutを長押し</span></div><div class="delete-instruction"><span class="delete-step">2</span><span>「Appを削除」をタップ</span></div><div class="delete-instruction"><span class="delete-step">3</span><span>もう一度「Appを削除」</span></div></div><p class="delete-sheet-note">この操作だけはiPhone側で行います。</p><button class="delete-sheet-primary" id="appDeletedBtn">削除した</button><button class="delete-sheet-secondary" id="appLaterBtn">あとで</button>`);document.getElementById("appDeletedBtn").onclick=()=>{appQueued=false;updateReview();closeDeleteSheet();go("photos")};document.getElementById("appLaterBtn").onclick=closeDeleteSheet}
function showPhotoDeleteOnly(){const count=queued.size;openDeleteSheet(`<div class="delete-sheet-title">写真・動画を削除</div><p class="delete-sheet-note">${count}枚を削除します。</p><button class="delete-sheet-primary" id="photoDeleteBtn">削除する</button><button class="delete-sheet-secondary" id="photoCancelBtn">キャンセル</button>`);document.getElementById("photoDeleteBtn").onclick=()=>{queued.clear();render();closeDeleteSheet();go("photos")};document.getElementById("photoCancelBtn").onclick=closeDeleteSheet}
function startDeleteFlow(){const count=queued.size;if(!count&&!appQueued)return;if(count&&appQueued){const bytes=[1.2,.82,3.8,2.1,5.4].reduce((sum,v,i)=>sum+(queued.has(i)?v:0),0);openDeleteSheet(`<div class="delete-sheet-title">削除を進める</div><div class="delete-flow-row"><span class="delete-step">1</span><div class="delete-flow-main"><strong>写真・動画 ${count}枚</strong><span>be minimalから削除</span></div><span class="delete-flow-size">${bytes.toFixed(1)} MB</span></div><div class="delete-flow-row"><span class="delete-step">2</span><div class="delete-flow-main"><strong>CapCut</strong><span>iPhoneで削除</span></div><span class="delete-flow-size">1.8 GB</span></div><button class="delete-sheet-primary" id="continueDeleteBtn">写真・動画を削除して続ける</button><button class="delete-sheet-secondary" id="deleteCancelBtn">キャンセル</button>`);document.getElementById("continueDeleteBtn").onclick=()=>{queued.clear();render();showAppDeleteGuide(true)};document.getElementById("deleteCancelBtn").onclick=closeDeleteSheet;return}if(count){showPhotoDeleteOnly();return}showAppDeleteGuide(false)}
const appCard=document.getElementById("appCard"),appTrash=appCard.querySelector(".app-trash");let asx=0,asy=0,alx=0,aly=0,alt=0,avx=0,avy=0,amode="pending",ax=0,ay=0,appDragging=false;
function appTrashHot(on){appTrash.style.transform=on?"translateX(-50%) scale(1.14)":"translateX(-50%)";appTrash.style.opacity=on?"1":""}
function queueApp(){if(appQueued)return;appQueued=true;vibrate();appCard.style.visibility="hidden";updateReview();showAppQueuedHint()}
function restoreApp(){appCard.animate([{transform:appCard.style.transform||"none",opacity:appCard.style.opacity||1},{transform:"translate3d(0,0,0) scale(1)",opacity:1}],{duration:130,easing:"cubic-bezier(.2,.78,.18,1)"}).onfinish=()=>{appCard.style.transform="";appCard.style.opacity="";appTrashHot(false)}}
function directAppLaunch(dx,vy){appTrashHot(true);const anim=appCard.animate([{transform:appCard.style.transform||"none",opacity:1},{transform:`translate3d(${dx*.12}px,-100vh,0) scale(.96)`,opacity:0}],{duration:Math.abs(vy)>.6?90:115,easing:"cubic-bezier(.12,.82,.16,1)",fill:"forwards"});anim.onfinish=queueApp}
function slingshotAppLaunch(x,y,vx,vy){appTrashHot(true);let px=x,py=y,svx=vx*.18,svy=Math.max(-120,vy*.18),last=performance.now(),detached=false,raf=0;const k=105,c=12.5;function tick(t){let dt=Math.min(.022,(t-last)/1000)*2;last=t;if(!detached){const ax2=-k*px-c*svx,ay2=-k*py-c*svy;svx+=ax2*dt;svy+=ay2*dt;px+=svx*dt;py+=svy*dt;if(py<=0&&svy<0){detached=true;svy=Math.min(svy,-(420+Math.max(0,y)*4.9)*2);svx+=-x*2.7}}else{svy-=220*dt;svx*=Math.pow(.992,dt*60);px+=svx*dt;py+=svy*dt}const away=Math.max(0,-py),opacity=1-Math.min(.9,Math.max(0,away-innerHeight*.18)/(innerHeight*.55));appCard.style.transform=`translate3d(${px}px,${py}px,0) scale(${1-Math.min(.1,away/innerHeight*.1)}) rotate(${Math.max(-5,Math.min(5,px/36))}deg)`;appCard.style.opacity=opacity;if(py<-appCard.offsetHeight-80||opacity<.05){cancelAnimationFrame(raf);queueApp();return}raf=requestAnimationFrame(tick)}raf=requestAnimationFrame(tick)}
appCard.addEventListener("pointerdown",e=>{if(appQueued)return;asx=alx=e.clientX;asy=aly=e.clientY;alt=performance.now();avx=avy=0;amode="pending";ax=ay=0;appDragging=false;appCard.setPointerCapture?.(e.pointerId)});
appCard.addEventListener("pointermove",e=>{if(appQueued)return;const now=performance.now(),dt=Math.max(8,now-alt),dx=e.clientX-asx,dy=e.clientY-asy,adx=Math.abs(dx),ady=Math.abs(dy);avx=(e.clientX-alx)/dt*1000;avy=(e.clientY-aly)/dt*1000;alx=e.clientX;aly=e.clientY;alt=now;if(amode==="pending"&&(adx>8||ady>8))amode=ady>adx*1.04?"vertical":"horizontal";if(amode!=="vertical")return;appDragging=true;if(dy>0){ax=resisted(dx*.32);ay=resisted(dy);appCard.style.transform=`translate3d(${ax}px,${ay}px,0) scale(${1+Math.min(.025,ay/7000)}) rotate(${Math.max(-4,Math.min(4,ax/30))}deg)`;appTrashHot(ay>36)}else{ax=dx*.05;ay=dy*.92;appCard.style.transform=`translate3d(${ax}px,${ay}px,0)`;appCard.style.opacity=String(Math.max(.55,1+dy/520));appTrashHot(dy<-26)}});
appCard.addEventListener("pointerup",e=>{if(appQueued)return;const dx=e.clientX-asx,dy=e.clientY-asy;if(!appDragging||amode!=="vertical"){restoreApp();return}if(dy>38){slingshotAppLaunch(ax,ay,avx,avy);return}if(dy<-40||(dy<-16&&avy<-.28)){directAppLaunch(dx,avy);return}restoreApp()});
appCard.addEventListener("pointercancel",restoreApp);
const screens={photos:document.getElementById("photosScreen"),apps:document.getElementById("appsScreen"),final:document.getElementById("finalScreen")};
function go(name){if(name==="final")updateReview();Object.entries(screens).forEach(([k,s])=>s.classList.toggle("active",k===name));document.querySelectorAll(".nav-btn").forEach(b=>b.classList.toggle("active",b.dataset.target===name))}
document.querySelectorAll(".nav-btn").forEach(b=>b.addEventListener("click",()=>go(b.dataset.target)));document.getElementById("topReview").addEventListener("click",()=>go("final"));document.getElementById("cancelBtn").addEventListener("click",()=>go("photos"));document.getElementById("deleteBtn").addEventListener("click",startDeleteFlow);
render();