(function(){
const {DATA,MODES}=window.KLabData;
function el(tag,attrs={},html=''){const n=document.createElement(tag);Object.entries(attrs).forEach(([k,v])=>{if(k==='class')n.className=v;else if(k==='dataset')Object.assign(n.dataset,v);else if(k.startsWith('aria-'))n.setAttribute(k,v);else if(k==='onclick')n.addEventListener('click',v);else n[k]=v});if(html!==undefined)n.innerHTML=html;return n}
function stateClass(s){return s==='CONFIRMED'?'confirmed':s==='UNKNOWN'?'unknown':'context'}
function detailHTML(item){return `<div class="detail"><span class="state ${stateClass(item.state)}">${item.state}</span> <span class="relation">${item.relation}</span><h3>${item.title}</h3><p>${item.body}</p>${item.weak?'<div class="weak-warning">この関連は文脈です。現在の事実を支持・確認する証拠として扱いません。</div>':''}<div class="why"><b>WHY CONNECTED</b><br>${item.why}<br><br><b>SOURCE</b> · ${item.source}</div></div>`}
function escape(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function makeSession(mode){return {mode,started:false,steps:[],saved:[],questions:[],current:null}}
const app={mode:null,meta:null,session:null,stage:null,body:null,sheet:null};
function logStep(id,label,relation='entry'){app.session.started=true;app.session.current=id;app.session.steps.push({id,label,relation,time:new Date().toLocaleTimeString('ja-JP',{hour:'2-digit',minute:'2-digit'})});updateTrail()}
function updateTrail(){const t=document.querySelector('.trail strong');if(!t)return;const s=app.session.steps.slice(-3).map(x=>x.label);t.textContent=s.length?s.join(' › '):'ARTICLE'}
function backStep(){if(app.session.steps.length<=1){exitDive();return}app.session.steps.pop();const prev=app.session.steps.at(-1);app.session.current=prev.id;updateTrail();window.KLabModes.renderMode(app.mode,prev.id,true)}
function openSheet(){const list=app.sheet.querySelector('.session-list');list.innerHTML='';const title=el('div',{class:'session-item'},`<small>SESSION</small><strong>${app.meta.name}</strong><span>${app.session.steps.length} steps · ${app.session.saved.length} saved · ${app.session.questions.length} open questions</span>`);list.append(title);app.session.steps.forEach((s,i)=>list.append(el('div',{class:'session-item'},`<small>STEP ${i+1} · ${escape(s.relation)} · ${escape(s.time)}</small><strong>${escape(s.label)}</strong>`)));if(app.session.saved.length)list.append(el('div',{class:'session-item'},`<small>SAVED DISCOVERIES</small><strong>${app.session.saved.map(escape).join(' / ')}</strong>`));if(app.session.questions.length)list.append(el('div',{class:'session-item'},`<small>OPEN QUESTIONS</small><strong>${app.session.questions.map(escape).join(' / ')}</strong>`));app.sheet.classList.add('open')}
function saveCurrent(){const s=app.session.steps.at(-1);if(!s)return;if(!app.session.saved.includes(s.label))app.session.saved.push(s.label);openSheet()}
function keepQuestion(q){if(!app.session.questions.includes(q))app.session.questions.push(q);openSheet()}
function exitDive(){app.stage.classList.remove('is-diving');document.querySelector('.article-scroll').scrollTop=app.stage.dataset.scroll||0}
function enterDive(){app.stage.dataset.scroll=document.querySelector('.article-scroll').scrollTop;app.stage.classList.add('is-diving');if(!app.session.started)logStep('start',app.meta.name,'anchor');window.KLabModes.renderMode(app.mode,'start',false)}
function articleHTML(){const thread=app.mode==='thread';const phrase=thread?`<button class="inline-thread" data-thread aria-label="海岸線の変化からDIVEを始める">海岸線の変化</button>`:`<span class="inline-plain">海岸線の変化</span>`;const entry=thread?`<div class="entry-zone thread-cue"><div class="entry-copy">本文の下線「海岸線の変化」から直接DIVEできます</div></div>`:`<div class="entry-zone"><div class="entry-copy">${app.meta.entryHint}</div><button class="entry-primary" data-enter><b>${app.meta.entry}</b><span>DIVE →</span></button></div>`;return `<div class="article-scroll"><article><div class="cover"><div class="cover-shade"></div><div class="cover-copy"><div class="eyebrow">DEMO DATA · VERIFIED SOURCES</div><h1>${DATA.anchor.title}</h1><p class="summary">${DATA.anchor.summary}</p></div></div><div class="body"><section><div class="eyebrow">WHAT HAPPENED</div><h2>地震そのものと、地形変化を分けて見る</h2><p>気象庁は2024年1月1日16時10分の地震をM7.6、最大震度7としている。一方、国土地理院は衛星データや現地調査から大きな地殻変動を報告した。</p><p>特に気になるのが ${phrase} だ。地震前後の観測画像を比較すると陸化した領域が確認され、輪島市西部では最大約4mの隆起が解析された。</p></section><section><div class="eyebrow">READ CAREFULLY</div><h2>「過去にもあった」は証拠ではない</h2><p>2007年にも能登半島沖でM6.9の地震があった。しかし、地域や現象が似ていることは、2024年の個別事実を証明しない。DIVEではこの違いを関係タイプとして残す。</p><div class="source-row"><span class="state confirmed">CONFIRMED</span><span class="state context">CONTEXT</span><span class="state unknown">UNKNOWN</span></div></section><section><div class="eyebrow">SOURCES</div>${DATA.sources.map(s=>`<p><b>${s.name}</b><br><span style="color:var(--muted);font-size:13px">${s.title} · ${s.note}</span></p>`).join('')}</section></div></article></div>${entry}`}
function baseDive(){app.body.innerHTML=`<div class="eyebrow">${app.meta.no} · ${app.meta.name}</div><h2>${app.meta.desc}</h2><p class="lead">2〜4操作で発見が起きる最小実験。関係タイプとソースを残したまま、もう一段深く進めます。</p><div id="modeRoot"></div>`;return document.getElementById('modeRoot')}
function showDetail(root,item,next){root.querySelectorAll('.detail').forEach(x=>x.remove());const wrap=el('div');wrap.innerHTML=detailHTML(item);const d=wrap.firstElementChild;if(next){const a=el('div',{class:'actions'});a.append(el('button',{class:'action primary',onclick:()=>{logStep(next.id,next.label,next.relation);window.KLabModes.renderMode(app.mode,next.id,false)}},'もう一段潜る'));if(item.state==='UNKNOWN')a.append(el('button',{class:'action',onclick:()=>keepQuestion(item.title)},'問いとして残す'));else a.append(el('button',{class:'action',onclick:saveCurrent},'この発見を保存'));d.append(a)}root.append(d);d.scrollIntoView({block:'nearest',behavior:'smooth'})}

window.KLabCore={DATA,MODES,el,stateClass,detailHTML,escape,makeSession,app,logStep,updateTrail,backStep,openSheet,saveCurrent,keepQuestion,exitDive,enterDive,articleHTML,baseDive,showDetail};
})();
