const safeStorage={get(k,f=null){try{const v=localStorage.getItem(k);return v===null?f:v}catch{return f}},set(k,v){try{localStorage.setItem(k,v)}catch{}}};
const ASSET={
  babel:'https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/The_Tower_of_Babel_%28Bruegel%29.jpg/960px-The_Tower_of_Babel_%28Bruegel%29.jpg',
  map1492:'https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/Colonisation_1492.png/960px-Colonisation_1492.png',
  liberty:'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/La_Libert%C3%A9_guidant_le_peuple_by_Eug%C3%A8ne_Delacroix.jpg/960px-La_Libert%C3%A9_guidant_le_peuple_by_Eug%C3%A8ne_Delacroix.jpg',
  columbus:'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/John_Vanderlyn_-_Columbus_Landing_at_Guanahani%2C_1492_-_WGA24269.jpg/960px-John_Vanderlyn_-_Columbus_Landing_at_Guanahani%2C_1492_-_WGA24269.jpg',
  ming:"https://commons.wikimedia.org/wiki/Special:Redirect/file/%27Boy_Riding_a_Goat%27%2C_15th-century_Ming_dynasty_Chinese_scroll_painting_by_L%C3%BC_Wenying.jpg",
  napoleon:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Jacques-Louis_David_-_The_Emperor_Napoleon_in_His_Study_at_the_Tuileries_-_Google_Art_Project.jpg?width=900',
  enlightenment:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Salon_de_Madame_Geoffrin.jpg?width=900',
  aztec:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Codex_Mendoza_folio_2r.jpg?width=900',
  ottoman:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Gentile_Bellini_003.jpg?width=900',
  songhai:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Great_Mosque_of_Djenn%C3%A9_1.jpg?width=900',
  ww1:'https://commons.wikimedia.org/wiki/Special:Redirect/file/The_Ypres_salienent_in_World_War_One.jpg?width=900',
  roman:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Colosseum_in_Rome%2C_Italy_-_April_2007.jpg?width=900',
  leonardo:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Leonardo_self.jpg?width=900',
  gutenberg:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Gutenberg_Bible_B42_Genesis.JPG?width=900',
  mongol:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Genghis_Khan%2C_Yuan_Dynasty.jpg?width=900'
};
const EVENTS={
  'french-revolution':{title:'フランス革命',year:'1789',tags:['革命','政治','ヨーロッパ'],image:ASSET.liberty,lead:'「国王が統治するのが当然」という前提が崩れ、市民・権利・国家の考え方を大きく変えた革命。',overview:['1789年、財政危機と身分制への不満を背景に、フランス社会は大きな政治変動へ入りました。革命は王権を制限し、やがて共和政へ進みます。','重要なのは、革命が一つの原因だけで起きたわけではないことです。社会構造、国家財政、食料価格、啓蒙思想、アメリカ独立革命の影響が同時に重なりました。'],why:[{type:'社会',class:'',title:'身分制への不満',items:['第三身分が人口の大半を占めながら政治的権利が弱かった','税負担が身分によって不均衡だった']},{type:'思想',class:'idea',title:'「権力は誰のものか」という問い',items:['啓蒙思想が自由・平等・人民主権を広げた','アメリカ独立革命が現実の政治変革の例になった']},{type:'経済',class:'econ',title:'国家と生活の危機',items:['戦争による巨額の国家債務','不作と食料価格上昇で都市生活者の不満が高まった']}],after:['革命はナポレオンの登場へつながり、フランス軍を通して法制度や国民国家の考え方がヨーロッパへ拡散しました。','その後の19世紀には自由主義・ナショナリズム・市民革命が各地で広がり、現代国家の形成にも長い影響を残します。']},
  'american-independence':{title:'アメリカ独立革命',year:'1776',tags:['革命','アメリカ','政治'],image:ASSET.columbus,lead:'植民地が本国からの独立を宣言し、共和政と権利の思想を世界政治に強く示した転換点。',overview:['北米13植民地はイギリス本国との課税・代表権をめぐる対立を深め、1776年に独立宣言を発表しました。'],why:[{type:'政治',title:'代表なき課税への反発',items:['植民地側に議会での代表がなかった','本国の統制強化への不満']},{type:'思想',class:'idea',title:'自然権と共和主義',items:['啓蒙思想の影響','統治の正当性を人民に置く考え']},{type:'経済',class:'econ',title:'商業統制への不満',items:['課税と貿易規制','植民地経済の成長']}],after:['独立はフランス革命を含む大西洋世界の革命運動に刺激を与えました。']},
  'napoleon':{title:'ナポレオンの登場',year:'1799',tags:['人物','政治','ヨーロッパ'],image:ASSET.napoleon,lead:'革命後の混乱から権力を握り、ヨーロッパの政治秩序を塗り替えた軍人・統治者。',overview:['1799年のクーデタで実権を握り、のち皇帝となりました。'],why:[{type:'政治',title:'革命後の不安定',items:['政権交代と政治的不信','強い統治への期待']},{type:'軍事',class:'idea',title:'軍事的成功',items:['若くして名声を得た','軍隊からの支持']},{type:'社会',class:'econ',title:'革命成果の固定',items:['法の下の平等','財産権の安定']}],after:['ナポレオン戦争はヨーロッパ各地で国民意識を刺激し、ウィーン体制の形成にもつながりました。']},
  'world-war-one':{title:'第一次世界大戦',year:'1914',tags:['戦争','帝国主義','世界'],image:ASSET.ww1,lead:'帝国・同盟・民族問題が結びつき、地域紛争が世界規模の総力戦へ拡大した戦争。',overview:['1914年、サラエボ事件をきっかけに欧州の同盟関係が連鎖し、戦争が世界規模へ拡大しました。'],why:[{type:'国際政治',title:'同盟の連鎖',items:['三国同盟と三国協商','危機時に参戦国が増える構造']},{type:'思想',class:'idea',title:'ナショナリズム',items:['民族自決と大国政治の衝突','バルカン半島の緊張']},{type:'帝国競争',class:'econ',title:'軍拡と植民地競争',items:['海軍・陸軍の軍拡','帝国主義的競争']}],after:['大戦は帝国の崩壊、ロシア革命、国境再編、そして第二次世界大戦へ続く不安定な国際秩序を生みました。']}
};
const HOME=[['french-revolution','なぜ革命は起きた？'],['american-independence','革命は海を越えた'],['napoleon','革命の後に現れた人物'],['world-war-one','なぜ世界戦争になった？']];
const YEARS=[
  {year:-3000,label:'BC3000',title:'都市と国家のはじまり',copy:'農耕社会から都市・文字・国家が現れ始める。',powers:['メソポタミア','古代エジプト','インダス前史','黄河文明前夜']},
  {year:476,label:'476',title:'西ローマ帝国の終焉',copy:'地中海世界の政治秩序が組み替わり、中世ヨーロッパへ。',powers:['東ローマ帝国','フランク諸勢力','ササン朝','グプタ朝後期']},
  {year:1200,label:'1200',title:'ユーラシアが再接続する時代',copy:'交易圏と遊牧帝国が広域世界を結び直していく。',powers:['南宋','ホラズム朝','アイユーブ朝','西欧諸王国']},
  {year:1492,label:'1492',title:'大航海時代の幕開け',copy:'大西洋の航路が世界のつながりを急速に変え始めた年。',powers:['カスティーリャ・アラゴン','オスマン帝国','明','ソンガイ帝国','アステカ','インカ']},
  {year:1789,label:'1789',title:'革命が政治の前提を変える',copy:'市民・権利・国家という考え方が大きく揺れ動く。',powers:['フランス王国→革命政府','清','オスマン帝国','ロシア帝国','イギリス']},
  {year:1914,label:'1914',title:'帝国の競争が世界戦争へ',copy:'同盟・軍拡・民族問題が結びつき、総力戦が始まる。',powers:['イギリス帝国','ドイツ帝国','ロシア帝国','オーストリア＝ハンガリー','オスマン帝国']},
  {year:2026,label:'2026',title:'現在は、歴史の途中',copy:'現代の国境・制度・対立も、過去の積み重ねの上にある。',powers:['国家','国際機関','企業','市民社会','デジタルネットワーク']}
];
const REGIONS_1492=[
  {place:'ヨーロッパ / 大西洋',title:'コロンブスの航海',copy:'カスティーリャ王権の支援で大西洋を横断。欧州とアメリカ大陸の関係が激変していく。',image:ASSET.columbus,event:null},
  {place:'東アジア',title:'明の時代',copy:'東アジアの巨大な農業・商業国家。海禁政策の一方で域内交易は活発だった。',image:ASSET.ming,event:null},
  {place:'西アフリカ',title:'ソンガイ帝国の繁栄',copy:'ニジェール川流域とサハラ交易を背景に、西アフリカ最大級の国家へ。',image:ASSET.songhai,event:null},
  {place:'中東・東地中海',title:'オスマン帝国の拡大',copy:'コンスタンティノープル征服後、東地中海とバルカンで勢力を拡大。',image:ASSET.ottoman,event:null},
  {place:'メソアメリカ',title:'アステカ帝国',copy:'テノチティトランを中心に、多数の都市国家を従える政治圏を形成。',image:ASSET.aztec,event:null}
];
const LIBRARY=[
  {type:'人物',title:'レオナルド・ダ・ヴィンチ',dates:'1452–1519',image:ASSET.leonardo},{type:'人物',title:'ナポレオン',dates:'1769–1821',image:ASSET.napoleon,event:'napoleon'},
  {type:'文明',title:'ローマ帝国',dates:'BC27–476',image:ASSET.roman},{type:'文明',title:'モンゴル帝国',dates:'1206–1368',image:ASSET.mongol},
  {type:'戦争',title:'第一次世界大戦',dates:'1914–1918',image:ASSET.ww1,event:'world-war-one'},{type:'思想・文化',title:'啓蒙思想',dates:'17–18世紀',image:ASSET.enlightenment},
  {type:'技術',title:'活版印刷',dates:'15世紀',image:ASSET.gutenberg},{type:'宗教',title:'宗教改革',dates:'16世紀',image:ASSET.babel},
  {type:'戦争',title:'フランス革命',dates:'1789–1799',image:ASSET.liberty,event:'french-revolution'},{type:'思想・文化',title:'アメリカ独立',dates:'1776',image:ASSET.columbus,event:'american-independence'}
];
const CATS=['すべて','人物','文明','戦争','思想・文化','技術','宗教'];
const PROGRESS=[['ヨーロッパ',78],['中東',54],['東アジア',61],['南アジア',43],['アフリカ',36],['南北アメリカ',57]];
let currentYear=1492,currentEvent='french-revolution',currentCat='すべて';
const scrollMemory={};
function routeNameFromHash(){const h=(location.hash||'#home').slice(1);if(h.startsWith('event/'))return 'event';return ['home','timeline','library','map','profile'].includes(h)?h:'home'}
function go(route){const current=routeNameFromHash();scrollMemory[current]=scrollY;if(route.startsWith('event/'))location.hash=route;else location.hash=route}
function applyRoute(){const route=routeNameFromHash();if(location.hash.startsWith('#event/')){currentEvent=location.hash.split('/')[1]||'french-revolution';renderEvent(currentEvent)}document.querySelectorAll('.screen').forEach(s=>s.classList.toggle('active',s.dataset.screen===route));document.querySelectorAll('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.route===route));document.getElementById('globalTopbar').hidden=route==='home';closeSheet();requestAnimationFrame(()=>scrollTo(0,scrollMemory[route]||0))}
function mediaState(root){root.querySelectorAll('.media img').forEach(img=>{const m=img.closest('.media');const done=()=>{m.classList.remove('failed');m.classList.add('loaded')};const fail=()=>{m.classList.remove('loaded');m.classList.add('failed');img.style.display='none'};if(img.complete){img.naturalWidth?done():fail()}else{img.addEventListener('load',done,{once:true});img.addEventListener('error',fail,{once:true})}})}
function cardMedia(src,alt=''){return `<div class="media"><img loading="lazy" src="${src}" alt="${alt}"><div class="media-fallback">資料画像を読み込めませんでした</div></div>`}
function renderHome(){homeCards.innerHTML=HOME.map(([id,kicker])=>{const e=EVENTS[id];return `<button class="quick-card tap" data-event="${id}"><div class="media"><img loading="lazy" src="${e.image}" alt="${e.title}"><div class="media-fallback">資料画像を読み込めませんでした</div></div><div class="quick-body"><div class="quick-meta">${kicker}</div><div class="quick-title">${e.title}</div><p class="quick-desc">${e.lead}</p></div></button>`}).join('');mediaState(homeCards)}
function renderYearPicker(){yearPicker.innerHTML=YEARS.map(y=>`<button class="year-chip ${y.year===currentYear?'active':''}" data-year="${y.year}">${y.label}</button>`).join('')}
function renderTimeline(){const y=YEARS.find(x=>x.year===currentYear)||YEARS[3];timelineYear.textContent=y.label;timelineEra.textContent=y.year<0?'BCE':'CE';timelineTitle.textContent=y.title;timelineCopy.textContent=y.copy;renderYearPicker();powerPills.innerHTML=y.powers.map(x=>`<span class="power-pill">${x}</span>`).join('');mapLabel.textContent=`${y.label}｜主要な世界勢力`;mapImage.src=ASSET.map1492;mapImage.alt=`${y.label}ごろの世界勢力を示す歴史地図`;const regs=currentYear===1492?REGIONS_1492:REGIONS_1492.map((r,i)=>({...r,place:y.powers[i%y.powers.length]||r.place,title:i===0?y.title:r.title,copy:i===0?y.copy:r.copy}));regionCards.innerHTML=regs.map(r=>`<button class="region-card tap" ${r.event?`data-event="${r.event}"`:''}><div class="media"><img loading="lazy" src="${r.image}" alt="${r.title}"><div class="media-fallback">資料画像を読み込めませんでした</div></div><div class="region-body"><div class="region-place">${r.place}</div><div class="region-title">${r.title}</div><p class="region-copy">${r.copy}</p></div></button>`).join('');mediaState(document.getElementById('screen-timeline'))}
function renderEvent(id){const e=EVENTS[id]||EVENTS['french-revolution'];currentEvent=id in EVENTS?id:'french-revolution';eventTitle.textContent=e.title;eventYear.textContent=e.year;eventLead.textContent=e.lead;eventImage.src=e.image;eventImage.alt=e.title;eventImage.style.display='block';eventTags.innerHTML=e.tags.map(t=>`<span class="tag">${t}</span>`).join('');eventOverview.innerHTML=e.overview.map(p=>`<p>${p}</p>`).join('');whyGrid.innerHTML=e.why.map(f=>`<div class="factor ${f.class||''}"><div class="factor-label">${f.type}</div><h3>${f.title}</h3><ul>${f.items.map(i=>`<li>${i}</li>`).join('')}</ul></div>`).join('');convergeEvent.textContent=e.title;eventAfter.innerHTML=e.after.map(p=>`<p>${p}</p>`).join('');document.querySelectorAll('.tab').forEach((b,i)=>b.classList.toggle('active',i===0));document.querySelectorAll('.tab-panel').forEach((p,i)=>p.classList.toggle('active',i===0));updateBookmark();renderGraph();mediaState(document.getElementById('screen-event'))}
function renderLibraryTabs(){libraryTabs.innerHTML=CATS.map(c=>`<button class="library-tab ${c===currentCat?'active':''}" data-cat="${c}">${c}</button>`).join('')}
function renderLibrary(){renderLibraryTabs();const list=currentCat==='すべて'?LIBRARY:LIBRARY.filter(x=>x.type===currentCat);libraryGrid.innerHTML=list.map((x,i)=>`<button class="library-card tap" ${x.event?`data-event="${x.event}"`:''}><div class="media"><img loading="lazy" src="${x.image}" alt="${x.title}"><div class="media-fallback">資料画像を読み込めませんでした</div></div><div class="library-card-body"><div class="type">${x.type}</div><h3>${x.title}</h3><div class="dates">${x.dates}</div></div></button>`).join('');mediaState(libraryGrid)}
function renderProgress(){regionProgress.innerHTML=PROGRESS.map(([n,v])=>`<div class="progress-row"><span>${n}</span><div class="progress-track"><div class="progress-fill" style="width:${v}%"></div></div><div class="progress-num">${v}%</div></div>`).join('')}
function getBookmarks(){try{return JSON.parse(safeStorage.get('chronos-bookmarks','[]')||'[]')}catch{return[]}}
function setBookmarks(v){safeStorage.set('chronos-bookmarks',JSON.stringify(v))}
function updateBookmark(){const saved=getBookmarks().includes(currentEvent);eventBookmark.classList.toggle('saved',saved);eventBookmark.setAttribute('aria-label',saved?'保存解除':'保存')}
function toggleBookmark(){let b=getBookmarks();if(b.includes(currentEvent)){b=b.filter(x=>x!==currentEvent);showToast('保存を解除しました')}else{b.push(currentEvent);showToast('保存しました')}setBookmarks(b);updateBookmark()}
function showBookmarks(){const b=getBookmarks();openSearch();searchInput.value='';searchResults.innerHTML=b.length?b.map(id=>{const e=EVENTS[id];return `<button class="search-result" data-event="${id}"><strong>${e.title}</strong><small>${e.year}｜保存済み</small></button>`}).join(''):'<p class="muted">保存した項目はまだありません。</p>'}
function setTheme(theme){document.documentElement.dataset.theme=theme;safeStorage.set('chronos-theme',theme);themeColor.content=theme==='dark'?'#171817':'#eee7d8';menuThemeText.textContent=theme==='dark'?'Dark':'Ivory';document.querySelectorAll('[data-theme-choice]').forEach(b=>b.classList.toggle('active',b.dataset.themeChoice===theme))}
function toggleTheme(){setTheme(document.documentElement.dataset.theme==='dark'?'light':'dark')}
function openSheet(){sheetBackdrop.classList.add('open');menuSheet.classList.add('open')}
function closeSheet(){sheetBackdrop.classList.remove('open');menuSheet.classList.remove('open')}
function openSearch(){searchOverlay.classList.add('open');setTimeout(()=>searchInput.focus(),120);renderSearch('')}
function closeSearch(){searchOverlay.classList.remove('open');searchInput.blur()}
function renderSearch(q){q=q.trim().toLowerCase();const eventItems=Object.entries(EVENTS).map(([id,e])=>({id,title:e.title,meta:`${e.year}｜${e.tags.join('・')}`}));const libItems=LIBRARY.filter(x=>!x.event).map(x=>({title:x.title,meta:`${x.dates}｜${x.type}`}));const list=[...eventItems,...libItems].filter(x=>!q||`${x.title} ${x.meta}`.toLowerCase().includes(q)).slice(0,20);searchResults.innerHTML=list.map(x=>`<button class="search-result" ${x.id?`data-event="${x.id}"`:''}><strong>${x.title}</strong><small>${x.meta}</small></button>`).join('')||'<p class="muted">該当する項目がありません。</p>'}
let toastTimer;function showToast(msg){toast.textContent=msg;toast.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove('show'),1700)}
function renderGraph(){const nodes=[
{id:'enlight',x:320,y:80,w:150,h:62,label:'啓蒙思想',year:'18世紀',event:null},{id:'american',x:105,y:160,w:175,h:64,label:'アメリカ独立革命',year:'1776',event:'american-independence'},{id:'finance',x:100,y:340,w:160,h:62,label:'財政危機と重税',year:'',event:null},{id:'fr',x:320,y:280,w:190,h:84,label:'フランス革命',year:'1789',event:'french-revolution',center:true},{id:'napoleon',x:545,y:355,w:170,h:64,label:'ナポレオンの登場',year:'1799',event:'napoleon'},{id:'nation',x:555,y:150,w:170,h:64,label:'国民国家の形成',year:'19世紀',event:null},{id:'rights',x:220,y:470,w:170,h:64,label:'人権思想の拡大',year:'',event:null},{id:'revolutions',x:485,y:490,w:180,h:64,label:'ヨーロッパの革命運動',year:'19世紀',event:null},{id:'ww1',x:650,y:455,w:160,h:64,label:'第一次世界大戦',year:'1914',event:'world-war-one'}];
const edges=[['enlight','fr','cause'],['american','fr','cause'],['finance','fr','cause'],['fr','napoleon','result'],['fr','rights','result'],['napoleon','nation','impact'],['nation','revolutions','impact'],['rights','revolutions','impact'],['revolutions','ww1','impact']];
const by=Object.fromEntries(nodes.map(n=>[n.id,n]));graphStage.innerHTML=`<svg viewBox="0 0 760 560" aria-label="フランス革命の因果関係マップ"><defs><marker id="arrowGold" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0,0 L8,4 L0,8 z" fill="var(--gold)"/></marker><marker id="arrowRust" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0,0 L8,4 L0,8 z" fill="var(--rust)"/></marker><marker id="arrowOlive" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0,0 L8,4 L0,8 z" fill="var(--olive)"/></marker></defs><g id="graphViewport">${edges.map(([a,b,t])=>{const A=by[a],B=by[b];return `<line class="edge ${t}" x1="${A.x}" y1="${A.y}" x2="${B.x}" y2="${B.y}" marker-end="url(#arrow${t==='cause'?'Gold':t==='result'?'Rust':'Olive'})"/>`}).join('')}${nodes.map(n=>`<g class="node ${n.center?'center':''}" transform="translate(${n.x} ${n.y})" ${n.event?`data-event="${n.event}"`:''}><ellipse rx="${n.w/2}" ry="${n.h/2}"/><text y="${n.year?-5:5}">${n.label}</text>${n.year?`<text class="year-text" y="17">${n.year}</text>`:''}</g>`).join('')}</g></svg>`;initGraphGestures()}
let graphTransform={x:0,y:0,s:1};function setGraphTransform(){const g=document.getElementById('graphViewport');if(g)g.setAttribute('transform',`translate(${graphTransform.x} ${graphTransform.y}) scale(${graphTransform.s})`)}function graphReset(){graphTransform={x:0,y:0,s:1};setGraphTransform()}function graphZoom(f){graphTransform.s=Math.max(.65,Math.min(2.2,graphTransform.s*f));setGraphTransform()}
function initGraphGestures(){const stage=graphStage;const pts=new Map();let start={x:0,y:0,tx:0,ty:0,dist:0,s:1,moved:false};stage.onpointerdown=e=>{stage.setPointerCapture?.(e.pointerId);pts.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pts.size===1)start={x:e.clientX,y:e.clientY,tx:graphTransform.x,ty:graphTransform.y,dist:0,s:graphTransform.s,moved:false};if(pts.size===2){const a=[...pts.values()];start.dist=Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y);start.s=graphTransform.s}};stage.onpointermove=e=>{if(!pts.has(e.pointerId))return;pts.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pts.size===1){const dx=e.clientX-start.x,dy=e.clientY-start.y;if(Math.abs(dx)+Math.abs(dy)>6)start.moved=true;graphTransform.x=start.tx+dx;graphTransform.y=start.ty+dy;setGraphTransform()}else if(pts.size===2){const a=[...pts.values()];const d=Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y);graphTransform.s=Math.max(.65,Math.min(2.2,start.s*(d/start.dist)));setGraphTransform()}};stage.onpointerup=e=>{pts.delete(e.pointerId)};stage.onpointercancel=e=>pts.delete(e.pointerId);stage.onwheel=e=>{e.preventDefault();graphZoom(e.deltaY<0?1.08:.92)}}
function handleClick(e){const route=e.target.closest('[data-route]');if(route){go(route.dataset.route);return}const ev=e.target.closest('[data-event]');if(ev&&ev.dataset.event){closeSearch();go('event/'+ev.dataset.event);return}const action=e.target.closest('[data-action]')?.dataset.action;if(action){if(action==='search')openSearch();if(action==='close-search')closeSearch();if(action==='theme')toggleTheme();if(action==='menu')openSheet();if(action==='back'){history.length>1?history.back():go('timeline')}if(action==='bookmark-current')toggleBookmark();if(action==='bookmarks')showBookmarks();return}const y=e.target.closest('[data-year]');if(y){currentYear=Number(y.dataset.year);renderTimeline();go('timeline');return}const tab=e.target.closest('[data-tab]');if(tab){document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b===tab));document.querySelectorAll('.tab-panel').forEach(p=>p.classList.toggle('active',p.id==='tab-'+tab.dataset.tab));return}const cat=e.target.closest('[data-cat]');if(cat){currentCat=cat.dataset.cat;renderLibrary();return}const theme=e.target.closest('[data-theme-choice]');if(theme){setTheme(theme.dataset.themeChoice);return}const graph=e.target.closest('[data-graph]');if(graph){if(graph.dataset.graph==='out')graphZoom(.85);if(graph.dataset.graph==='reset')graphReset();if(graph.dataset.graph==='full')graphShell.classList.toggle('fullscreen');return}}
document.addEventListener('click',handleClick);sheetBackdrop.addEventListener('click',closeSheet);searchInput.addEventListener('input',()=>renderSearch(searchInput.value));window.addEventListener('hashchange',applyRoute);
let edgeSwipe=null;window.addEventListener('touchstart',e=>{const t=e.touches[0];if(t.clientX<22)edgeSwipe={x:t.clientX,y:t.clientY}},{passive:true});window.addEventListener('touchend',e=>{if(!edgeSwipe)return;const t=e.changedTouches[0],dx=t.clientX-edgeSwipe.x,dy=Math.abs(t.clientY-edgeSwipe.y);if(dx>86&&dy<70)history.back();edgeSwipe=null},{passive:true});
setTheme(safeStorage.get('chronos-theme','dark')||'dark');renderHome();renderTimeline();renderLibrary();renderProgress();renderEvent(currentEvent);if(!location.hash)history.replaceState(null,'','#home');applyRoute();mediaState(document);
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));