function bind(){document.querySelectorAll('[data-switch]').forEach(b=>b.onclick=()=>{current=Number(b.dataset.switch);state=load(current);history.replaceState(null,'',`?demo=${current}`);render()});document.querySelectorAll('[data-act]').forEach(b=>b.onclick=()=>action(b.dataset.act));document.querySelectorAll('[data-source]').forEach(b=>b.onclick=(e)=>{e.stopPropagation();openSource(b.dataset.source)});document.querySelectorAll('[data-step]').forEach(b=>b.onclick=()=>step(b.dataset.step));document.querySelectorAll('[data-braid]').forEach(b=>b.onclick=()=>stepBraid(Number(b.dataset.braid)));document.querySelectorAll('[data-worm]').forEach(b=>b.onclick=()=>stepWorm());document.querySelectorAll('[data-radius]').forEach(i=>i.oninput=()=>setRadius(Number(i.value)));document.querySelectorAll('[data-cascade]').forEach(b=>b.onclick=()=>stepCascade(b.dataset.cascade));document.querySelectorAll('[data-pin]').forEach(b=>b.onclick=()=>pin(Number(b.dataset.pin)));document.querySelectorAll('[data-place]').forEach(b=>b.onclick=()=>setPlace(Number(b.dataset.place)));document.querySelectorAll('[data-time]').forEach(b=>b.onclick=()=>setTime(Number(b.dataset.time)));document.querySelectorAll('[data-zoom]').forEach(i=>i.oninput=()=>setZoom(Number(i.value)));document.querySelectorAll('[data-zoomstep]').forEach(b=>b.onclick=()=>setZoom(Math.max(0,Math.min(5,(state.concept.zoom??0)+Number(b.dataset.zoomstep)))));document.querySelectorAll('[data-clause]').forEach(b=>b.onclick=()=>clause(Number(b.dataset.clause)));}
function action(a){if(a==='enter'){state.articleScrollY=Math.max(0,window.scrollY||0);state.stage='explore';render();scrollTo({top:0});return}if(a==='article'){const y=state.articleScrollY||0;state.stage='article';save();render();requestAnimationFrame(()=>scrollTo({top:y}));return}if(a==='theme'){const html=document.documentElement;html.dataset.theme=html.dataset.theme==='dark'?'light':'dark';return}if(a==='back'){if(state.route.length){state.route.pop();const prev=state.route.at(-1);state.concept=prev?.concept?JSON.parse(JSON.stringify(prev.concept)):{};state.depth=prev?.depth||0;state.resume=prev?.label||'anchor';save();render()}return}if(a==='trail'){openTrail();return}if(a==='history'){openHistory();return}}
function step(kind){if(kind==='tunnel'){const n=(state.concept.tunnel||0)+1;state.concept.tunnel=Math.min(4,n);if(n===4)discovery('保守ログへの横道');push(['WHY','CLAIM','EVIDENCE','ASSUMPTION'][Math.min(n-1,3)],['claims','supports','context_for','context_for'][Math.min(n-1,3)],n===2?'ops-observation':'fixture')}if(kind==='peel'){state.concept.peel=Math.min(4,(state.concept.peel||0)+1);push(['ACTORS','CLAIMS','EVIDENCE','ORIGIN'][state.concept.peel-1],['part_of','claims','supports','source_of'][state.concept.peel-1],state.concept.peel===4?'origin-log':'fixture')}}
function stepBraid(i){const b=state.concept.braid||[0,0,0];if(b[i]<2){b[i]++;state.concept.braid=b;push(`${['CABLE','VESSEL','WEATHER'][i]} step ${b[i]+1}`,'context_for','braid-cross')}}
function stepWorm(){state.concept.worm=Math.min(3,(state.concept.worm||0)+1);const w=state.concept.worm;push(['NorthLink Cable','Repeater R-22','Supplier bulletin'][w-1],w===2?'historically_similar_to':w===3?'source_of':'part_of',w===3?'supplier-bulletin':'fixture')}
function setRadius(v){const prev=state.concept.radius??0;state.concept.radius=v;if(v>prev){const entry={id:`s${Date.now()}-${state.journey.length}`,parentStepId:state.route.at(-1)?.id||null,label:`Semantic radius ${v+1}`,relation:'context_for',at:Date.now(),depth:v+1,concept:JSON.parse(JSON.stringify(state.concept))};state.route.push(entry);state.journey.push(entry);state.depth=Math.max(state.depth,v+1);state.persisted=true;state.resume=entry.label;save()}render()}
function stepCascade(side){const c=state.concept.cascade||{past:0,future:0};if(c[side]<2){c[side]++;state.concept.cascade=c;push(`${side==='past'?'Past cause':'Future impact'} ${c[side]+1}`,side==='past'?'caused_by':'affects',side==='past'?'cause-log':'capacity-note')}}
function pin(i){let p=state.concept.pins||[];if(!p.includes(i)){p=[...p,i];state.concept.pins=p;const types=['supports','supports','contradicts','context_for'];push(`Evidence thread ${i+1}`,types[i],['ops-observation','repeater-diagnostic','maritime-note','maintenance-plan'][i])}}
function setPlace(v){const prev=state.concept.place??0;state.concept.place=v;if(v!==prev)push(`Place: ${['陸上監視局','Sector N-14','作業船 Aster'][v]}`,'context_for',v===2?'ais-fixture':'fixture')}
function setTime(v){const prev=state.concept.time??0;state.concept.time=v;if(v!==prev)push(`Time: ${['01:50','02:10','02:30','03:00'][v]} UTC`,'part_of','fixture')}
function setZoom(v){const prev=state.concept.zoom??0;state.concept.zoom=v;if(v!==prev){const entry={id:`s${Date.now()}-${state.journey.length}`,parentStepId:state.route.at(-1)?.id||null,label:`Scale: ${['WORLD','COUNTRY','ORG','PERSON','STATEMENT','PRIMARY'][v]}`,relation:v===5?'source_of':v===4?'claims':'part_of',at:Date.now(),depth:v,concept:JSON.parse(JSON.stringify(state.concept))};state.route.push(entry);state.journey.push(entry);state.depth=v;state.persisted=true;state.resume=entry.label;save()}render()}
function clause(i){let c=state.concept.clauses||[];if(!c.includes(i)){c=[...c,i];state.concept.clauses=c;push(`Contradiction clause ${i+1}`,i===2?'context_for':'contradicts',i===2?'origin-log':'maritime-note')}}
function rewindConcept(){switch(current){case 1:state.concept.tunnel=Math.max(0,(state.concept.tunnel||0)-1);break;case 2:{let b=state.concept.braid||[0,0,0];const idx=b.findLastIndex(x=>x>0);if(idx>=0)b[idx]--;state.concept.braid=b;break}case 3:state.concept.peel=Math.max(0,(state.concept.peel||0)-1);break;case 4:state.concept.worm=Math.max(0,(state.concept.worm||0)-1);break;case 5:state.concept.radius=Math.max(0,(state.concept.radius||0)-1);break;case 6:break;case 7:{let p=state.concept.pins||[];p.pop();state.concept.pins=p;break}case 8:break;case 9:state.concept.zoom=Math.max(0,(state.concept.zoom||0)-1);break;case 10:{let c=state.concept.clauses||[];c.pop();state.concept.clauses=c;break}}}